### ISSUE TITLE
Netmiko send_config_set() does not work properly with cumulus devices

### ISSUE THREAD

**Issue by sindhujit1** [ktbyers/netmiko#1579]
I tried pushing multiple commands as a list using send_config_set(), but I get an error 
`Unable to find prompt:`
I cannot even send any other parameters like expect_string or delay_factor as send_config_set() just seems to accept only one list of commands.

**Comment by ktbyers** [comment]
You need to post the full exception stack trace and your relevant code.

**Comment by sindhujit1** [comment]
```
try:
        vlan_commands = ['net add vlan xxxvlan-id xxx','net add vlan xxx vlan-raw-device bridge',
        'net add vlan xxx alias sample']
        vlan_commands_response = json.loads(net_connect.send_config_set(vlan_commands))
        print(vlan_commands_response,"vlan_commands_response")

    except Exception as e:

        exc_type, exc_obj, tb = sys.exc_info()
        f = tb.tb_frame
        lineno = tb.tb_lineno
        filename = f.f_code.co_filename
        linecache.checkcache(filename)
        line = linecache.getline(filename, lineno, f.f_globals)
        errorValidationMessage.append('Command For Posting VLAN Failed:' + str(e) + "Error On file "+filename + " Line Number "+str(lineno))
        print('Command For Posting VLAN Failed:' + str(e) + "Error On file "+filename + " Line Number "+str(lineno))
```

I just get the following error:
`Command For Posting VLAN Failed:Unable to find prompt: Error On file xxxx Line Number 306`

**Comment by ktbyers** [comment]
Yes, you are hiding the exception. You need to get rid of your exception handling and let the real exception occur.

**Comment by sindhujit1** [comment]
Ok i removed the exception, and it seemed to me that I needed to add a delay factor. However still I am getting the same error
```
Traceback (most recent call last):
  File "xxx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "xxx/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "xxx/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "xxx/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sgang31/netadc3/ztp/views.py", line 303, in postCutsheet_cumulus
    vlan_commands_response = json.loads(net_connect.send_config_set(vlan_commands))
  File "xxx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 53, in send_config_set
    config_commands=config_commands, exit_config_mode=exit_config_mode, **kwargs
  File "xxx/lib/python3.6/site-packages/netmiko/base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "xxx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 62, in config_mode
    return self.enable(cmd=config_command)
  File "xxx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 94, in enable
    self.set_base_prompt()
  File "xxx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 45, in set_base_prompt
    delay_factor=delay_factor,
  File "xxx/lib/python3.6/site-packages/netmiko/base_connection.py", line 1066, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "xxx/lib/python3.6/site-packages/netmiko/base_connection.py", line 1107, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt:
```

**Comment by ktbyers** [comment]
You might need to turn on Netmiko logging to see what is going on:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

Basically, it looks like it is unable to determine the trailing prompt. It is not clear why...

**Comment by sindhujit1** [comment]
I looked at the linux document and tried using exit_config_mode=False, but that did not work. Here are the logs below:

Basically it authenticates first successfully and then I get :

`DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
ERROR:django.request:Internal Server Error: /netadc3/ztp/postCutsheet_cumulus/
Traceback (most recent call last):
  File "xx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "xx/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "xx/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "xx/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sgang31/netadc3/ztp/views.py", line 307, in postCutsheet_cumulus
    vlan_commands_response = json.loads(net_connect.send_config_set(vlan_commands))
  File "xx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 53, in send_config_set
    config_commands=config_commands, exit_config_mode=exit_config_mode, **kwargs
  File "xx/lib/python3.6/site-packages/netmiko/base_connection.py", line 1607, in send_config_set
    output = self.config_mode(*cfg_mode_args)
  File "xx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 62, in config_mode
    return self.enable(cmd=config_command)
  File "xx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 94, in enable
    self.set_base_prompt()
  File "xx/lib/python3.6/site-packages/netmiko/linux/linux_ssh.py", line 45, in set_base_prompt
    delay_factor=delay_factor,
  File "xx/lib/python3.6/site-packages/netmiko/base_connection.py", line 1066, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "xx/lib/python3.6/site-packages/netmiko/base_connection.py", line 1107, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt:`

**Comment by ktbyers** [comment]
Try adding the following argument to ConnectHandler:

```
default_enter = '\r\n'
```

**Comment by sindhujit1** [comment]
same issue.
`net_connect = netmiko.ConnectHandler(device_type='linux', ip='x.x.x.x', username='xxx',password='xxx', port=22, verbose=False,default_enter = '\r\n')`

**Comment by ktbyers** [comment]
Okay, so the question is...why is this Linux box not responding when we send an `enter`?

We hit `enter` here 6 or 7 times and there is no response?

```
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M

DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: ^M
```

You might want to try setting `global_delay_factor: 2` or `4` and seeing if that makes a difference.

Can you show me what a manual CLI session for this looks like on Cumulus. In other words, if you did these changes manually what does the SSH-CLI session look like?

**Comment by sindhujit1** [comment]
So I added global_delay_factor = 4 in the netmiko connecthandler and we get a different error now.

 ```
 raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: '[sudo] password for cumulus:
```

After that I have added :
`sudo_response = net_connect.send_command("sudo su", expect_string=':')
 sudo_accept = net_connect.send_command('xxxx', expect_string='#')`

After doing this, I get the error :
`netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.`

The cumulus device prompt works just normally. Follolwing commands are added:

`cumulus@xxxx:mgmt-vrf:~$ net add vlan xxx vlan-id xxx
cumulus@xxxx:mgmt-vrf:~$ net add vlan xxx vlan-raw-device bridge
cumulus@xxxx:mgmt-vrf:~$ net add vlan xxx alias sample
cumulus@xxxx:mgmt-vrf:~$ `

**Comment by ktbyers** [comment]
Comment from earlier:

```
TypeError: send_config_set() got an unexpected keyword argument 'enter_config_mode'
```

Which version of Netmiko are you using?

**Comment by sindhujit1** [comment]
`(xxx) [xxx@xxx xxx]$ pip freeze | grep netmiko
netmiko==2.4.2`

**Comment by ktbyers** [comment]
You need to be testing against the latest version of Netmiko (i.e. 3.0.0).

Then try this again with send_config_set:

```
 "enter_config_mode=False"
```

If you get an error, please post your entire stack trace.

**Comment by sindhujit1** [comment]
Now I get a different error

`vlan_commands_response = net_connect.send_config_set(vlan_commands,enter_config_mode=False)
  File "xxx/lib/python3.6/site-packages/netmiko-3.0.0-py3.6.egg/netmiko/linux/linux_ssh.py", line 51, in send_config_set
    config_commands=config_commands, exit_config_mode=exit_config_mode, **kwargs
  File "xxx/lib/python3.6/site-packages/netmiko-3.0.0-py3.6.egg/netmiko/base_connection.py", line 1727, in send_config_set
    output += new_output
UnboundLocalError: local variable 'output' referenced before assignment`

**Comment by ktbyers** [comment]
That was fixed here:

https://github.com/ktbyers/netmiko/pull/1557

Why are you using `send_config_set`? What are you trying to do?

That is a bit of a strange operation with "linux" device_type. 

Note, the Linux device_type is mostly provided for compatibility for use-cases where you are already using Netmiko for other networking platforms (for example, when you need to bounce through a Linux box to get to other platforms).

It is not well-suited as a primary configuration management tool on Linux.

**Comment by sindhujit1** [comment]
Actually we are using cumulus devices and they are Dell devices. Its all cumulus linux so we use linux as the standard config mode for type of device . It works without any issue for send_command, for example :

`net_connect.send_command("netshow vlan json")`

its just creating issues for send_config_set(). The reason I want to use send_config_set() is we want a list of commands to be pushed at once, and as per my research thats only possible through this command.

**Comment by ktbyers** [comment]
Just use a `for-loop` and `send_command`.

But that fix I referenced above should fix  the `output` issue.

**Comment by sindhujit1** [comment]
Thats what I thought I would do if this did not work . 
But I still receive the same error even with netmiko 3.0.0 

`File "xxx/netadc_sgang31/lib/python3.6/site-packages/netmiko-3.0.0-py3.6.egg/netmiko/base_connection.py", line 1727, in send_config_set
    output += new_output
UnboundLocalError: local variable 'output' referenced before assignment`

**Comment by ktbyers** [comment]
@sindhujit1:

```
File "xxx/netadc_sgang31/lib/python3.6/site-packages/netmiko-3.0.0-py3.6.egg/netmiko/base_connection.py", line 1727, in send_config_set output += new_output UnboundLocalError: local variable 'output' referenced before assignment
```

This issue looks clearly like you are not using the `develop` branch.

This second issue I need the Netmiko log to provide any more information into:

```python
sudo_response = net_connect.send_command("sudo su", expect_string=':') 
sudo_accept = net_connect.send_command(device_ppassword, expect_string='#')
```

**Comment by ktbyers** [comment]
I am going to close as not having enough information on this. If there is still an issue, we should create a new issue in GitHub on it.
