### ISSUE TITLE
Long hostname causes Pattern not detected when in config mode

### ISSUE THREAD

**Issue by brianatlarge** [ktbyers/netmiko#2755]
I have a few Cisco IOS-XE switches with particularly long hostnames. For example, one may be:

`THIS.IS.A.PARTICULARLY.LONG`

When in a normal enabled prompt, it looks like this;

`THIS.IS.A.PARTICULARLY.LONG#`

But when in configuration mode, it's displayed as this:

`THIS.IS.A.PARTICULAR(config)#`

Due to hostname getting truncated by the way the switch displays long hostnames in config mode, Netmiko can't seem to successfully run configuration commands because it can't match the expected prompt. The result looks like this:

```
Connecting to THIS.IS.A.PARTICULARLY.LONG at 172.16.10.50
Connected...
Sending config set
Traceback (most recent call last):
  File "c:\Python\scripts\update_snmp_acl.py", line 90, in <module>
    updatesnmp(thisswitch)
  File "c:\Python\scripts\update_snmp_acl.py", line 81, in updatesnmp
    output = net_connect.send_config_set(newconfig, read_timeout=30)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 2137, in send_config_set
    output += self.config_mode()
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\cisco_base_connection.py", line 47, in config_mode
    return super().config_mode(
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 1976, in config_mode
    output += self.read_until_prompt(read_entire_line=True)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 734, in read_until_prompt
    return self.read_until_pattern(
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 651, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout:

Pattern not detected: 'THIS\\.IS\\.A\\.PARTICULARLY.\\LONG\\#' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

My script looks like this:

```
device = {
            'device_type': 'cisco_ios',
            'host': '172.16.10.50',
            'username': '****',
            'password': '****',
            "session_log": "output.txt"
        }
        net_connect = ConnectHandler(**device)
        newconfig = [
            'access-list 100 permit 10.1.1.1',
            'access-list 100 permit 10.1.1.2',
            'access-list 100 permit 10.1.1.3'
        ]
        output = net_connect.send_config_set(newconfig, read_timeout=30)
        print(output)
        output = net_connect.save_config()
        print(output)
        net_connect.disconnect()
```

**Comment by ktbyers** [comment]
I think that was probably fixed here:

https://github.com/ktbyers/netmiko/pull/2720

You should be able to test this with the Netmiko `develop` branch.

**Comment by brianatlarge** [comment]
Yep, that was it. Going from 4.0.0 to 4.0.1a1 fixed it.

**Comment by ktbyers** [comment]
@brianatlarge Sounds good. I am probably going to release that shortly as a new Netmiko release.

**Comment by hollymolly98** [comment]
@ktbyers has this issue being addressed. I'm running:
Python 3.10.6
netmiko '4.2.0'
and still facing this issue,
thanks
